### ISSUE TITLE
Clients on Virtual Wireless Interface are not included

### ISSUE THREAD

**Issue by boxintense** [vortex-5/ddwrt-bwmon#10]
Hello,

It seems that clients on virtual wireless interface are not included into the bwmon.

**Comment by vortex-5** [comment]
Currently only devices on BR0 I believe show up.

Do you know what virtual interfaces show up as in ip tables.

It might lead to a patch if you did.

**Comment by nafmee** [comment]
The same happened to me, I can't see the clients of br2 on bwmon interface.
Is it a bug or bwmon does not monitor virtual interfaces yet?
Thanks in advance.

**Comment by vortex-5** [comment]
Bwmon does not currently monitor virtual interfaces. 

It uses the nvram variable lanface to determine which interface is lan (br0 or 1) because you can have arbitrarily many virtual interfaces this has not been implemented yet. 

Virtual interface support may come but will require manual configuration most likely to work.

**Comment by vortex-5** [comment]
If you feel like trying yourself I would look at bwmon-running.sh and start.sh and where lanface is reference to see where support for virtal interfaces may be put in.

**Comment by vortex-5** [comment]
So I have not yet supported virtual interfaces but I've provided some new patches on the master branch that tries and addresses your devices on BR other than 0 problem.

If want to test these early you can try downloading them directly from master the files are bwmon.sh and /www/bwreader.php

I have not yet created a package for them yet as I'm still testing these myself to ensure stability. Please let me know if you want to be able to test it I will put up a beta version in the releases section so you can test them early. Generally speaking I have a testing period of 1 month before I release. 

This might be overly conservative but  routers generally aren't things people are happy with if they go down / lock up.

**Comment by vortex-5** [comment]
Should be resolved in this version no futher reports of this problem.
