### ISSUE TITLE
Bug: 404 error requesting bwreader.php

### ISSUE THREAD

**Issue by fseto** [vortex-5/ddwrt-bwmon#12]
Firmware: DD-WRT v24-sp2 (01/03/14) kongac
Router: Asus RT-AC66U
Lighttpd Enabled: No

Navigating to http://router/user/bwmon.html loads the HTML, CSS and JS successfully, however no bandwidth data is displayed. The browser inspection tool shows bwreader.php returning a 404.

Navigating to http://router/user/bwreader.php returns an empty response (ERR_EMPTY_RESPONSE).

**Comment by vortex-5** [comment]
Getting a 404 on bwreader.php is completely normal if you have lighttpd disabled. In fact it's how the script checks if the service is running to begin with by trying to access bwreader.php.

If the script doesn't see the service you will notice a countdown timer from 10. If it is using the service it will display no such timer as you will see updates every second.

As for your page not loading you there's probably another issue at play you may want to see the tmp/www folder exists for your router model.

additionally there's a usage_stats.js and a usage.js that should be in /tmp/www/

those must be accessable via router/user/usage_stats.js router/user/usage.js

Those inability to access those will be the most likely reason the monitor isn't working for you.

**Comment by fseto** [comment]
Thank you for responding Fan.

Both usage.js and usage_stats.js exist inside /tmp/www, however, they appear to be empty files (0 bytes). Both http://router/user/usage.js and http://router/user/usage_stats.js return 200 OK status.

I also noticed when running stop.sh, I get the following error:
cp: can't create '/jffs/bwmon/data/usage.js': No such file or directory
Creating the "data" directory resolves this but then start.sh will complain when it tries to recreate it. Perhaps backup.sh can be updated to create the data directory if it doesn't exist and start.sh can check the directory before creating.

**Comment by vortex-5** [comment]
Hi sorry I will be on vacation for a week so I won't have internet until
after.

**Comment by vortex-5** [comment]
start.sh should already crate the data directory for you:

https://github.com/vortex-5/ddwrt-bwmon/blob/master/bwmon/start.sh#L8

note:

```bash
if [ -d $SCRIPT_DIR/data ]
then
	mkdir $SCRIPT_DIR/data
fi
```

also startup.sh is the script that you should be calling during normal operation it's the same as start.sh but it prevents multiple instances from being run.
