### ISSUE TITLE
Feature: Allow toggling for megabits to megabytes

### ISSUE THREAD

**Issue by vortex-5** [vortex-5/ddwrt-bwmon#16]
There are users that prefer to see the rates in Megabits others in Megabytes add a toggle to allow for switching between the two.

Code change: 

Most likely the rate calculation functions will stay the same however the conversion will end up happening in the function that generates the mbps postfix and perform the correct conversion from there.

The UI will also probably need a toggle button and a cookie to store the last used display mode.

**Comment by AleXndrTheGr8st** [comment]
I'd like to bump this up, I currently have my version modified to brute force it to MB/s, I wouldn't mind if there was no toggle button but was instead a config option easily accessible somewhere in the code (no cookie necessary) :)

**Comment by vortex-5** [comment]
The design of features in the main code base is for every user so a friendly ui toggle needs to exist and it has to be switchable on the fly.

It also needs to remember where you left the toggle when you leave the page.

It's on my todo list seeing how this is the only item it will be done next don't have a lot of free time recently but that should change in a few weeks.

**Comment by boxintense** [comment]
Definitely big double thumbs up from me as well!

**Comment by vortex-5** [comment]
Yes I'll be working on this next I've haven't had a large block of free time. However I do expect that this to be done before the end of the month.

**Comment by vortex-5** [comment]
Ok well that didn't happen I'll try and block out some time so I can work on this soon

**Comment by vortex-5** [comment]
Release 1.8.0 is up with this feature.
