### ISSUE TITLE
When running stop.sh the backup.sh runs and chews cpu

### ISSUE THREAD

**Issue by danmed** [vortex-5/ddwrt-bwmon#17]
When i run stop.sh to kill everything, my CPU usage ramps up.. i have to manually kill the bwmon-autobackup.sh, bwmon-running.sh files

**Comment by vortex-5** [comment]
execute:

killall autobachup.sh 
killall bwmon-running.sh 

do you get any errors?

**Comment by danmed** [comment]
no errors, however running top shows that these are still running : 

 4036     1 root     S     1164  8.8  0.0 /bin/sh /tmp/smbshare/bwmon/bwmon-running.sh
 4037     1 root     S     1164  8.8  0.0 /bin/sh /tmp/smbshare/bwmon/bwmon-autobackup.sh

**Comment by vortex-5** [comment]
You are running these on a network drive as evidence by them being in smbshare.

This is not a configuration that was tested.

That said killall should kill any process with a matching string the fact that it's not doing that for you is the problem if you can figure out why killall is not working for you I can probably work out a hotfix.

**Comment by danmed** [comment]
I am yes, my router does not have a USB stick.. i'll see if i can figure out why killall isn't working.

In general though, the CPU does eventually max out.. is there any way around that?

**Comment by vortex-5** [comment]
If killall is not working you are running extra processes.

There should only be one process for bwmon but if it's unable to shut them down startup.sh will only open new processes without being able to shut down existing processes.

**Comment by vortex-5** [comment]
So far you are the first person to report this issue:

At worse we should document the:

Router Model:
Revision:
FIrmware Used:
Chipset: Broadcom / Atheros

**Comment by danmed** [comment]
Router Model : Netgear WNR834B
Revision : V2
Firmware Used : DD-WRT v24-sp1 (07/27/08) std
Chipset : Broadcom

**Comment by vortex-5** [comment]
Firmware specifically we're looking for the SVN version number.

But regardless killall doesn't seem to work the same in that version.

**Comment by danmed** [comment]
Sorry, SVN revision 10011

**Comment by vortex-5** [comment]
That's a pretty old version I'm running this on 29114 atheros released around 2016-02-20

**Comment by danmed** [comment]
yeah, i realised how old that was as i pasted it to you.. i'm trying to update to a later beta now.. i was almost sure i flashed it earlier but for some reason it did not take.

**Comment by danmed** [comment]
hmm.. i just tried again and it's still sat at the same revision... what's going on..

**Comment by vortex-5** [comment]
normally you would find the new versions from the ftp or the forums but they are currently down right now at dd-wrt so you'll have to wait until later to be able to get a copy.

**Comment by danmed** [comment]
THanks, i managed to get the router up to the latest but unfortunately it will only take the Mini firmware.. i've ordered a new router which should arrive today which will hopefully be better suited

**Comment by vortex-5** [comment]
I'm not sure about the high cpu usage but kill all not working is generally not good. It's used in other parts of the script I think to shut down services before restarting them to prevent infinite service spawning.

**Comment by vortex-5** [comment]
In terms of router requirements if you're making a new purchase something with 32MB of flash allows you to run the most feature rich firmware.

I'm not sure which versions fo ddwrt includes the lighttpd server however routers that will run that module get the best performance from this tool. The 32MB of flash routers usually do include these features.

However there are enough people that expressed concern when I was making a lighttpd only version that I know the normal non lighttpd version also works adequately.

**Comment by danmed** [comment]
Just thought i would let you know, i bricked my new router trying to find a firmware that allowed mounting to a network share :)

So i went back to my old one. Managed to get a firmware from 2011 on there and bwmon is working much better now.. thanks for your help

**Comment by vortex-5** [comment]
Technically since I started writing this in 2015 the oldest firmware it officially supports would be from that era. However it's nice to hear that it still supports firmware from a few years older than that.

**Comment by danmed** [comment]
Any recommendation for a new router? I'm a bit concerned as DD-WRT seem to remove features from their firmware for certain devices.. I need CIFS mounting or a USB port... i also don't want to spend a fortune :)

**Comment by vortex-5** [comment]
I haven't kept up on router tech lately. this might be a better question for the DDWRT forums.

From what I've seen Atheros units tend to have better support for kernels since they are open sourced where broadcom still has binary blobs for their drivers.

Aside from that it's usually a good idea to pick a semi popular model since the software support will be rolled out the fastest and will be the most tested.

The DDWRT Forums on Broadcom Based and Qualcomm Atheros WiSoc based hardware sub forums has the most active communities testing leading edge firmware it gives you an idea of what's available. Beyond that if you're on the FTP you can judge the firmware feature set by looking at the average firmware size for that router.

30MB and above tend to be all the features

16MB tends to have a subset

4MB tends to be the micro

but you can ask the community for specific features such as SMB and USB support
