### ISSUE TITLE
Live Bandwidth Stats ERROR

### ISSUE THREAD

**Issue by hcater** [vortex-5/ddwrt-bwmon#22]
Thank you for putting this all together :)

I'm running  DD-WRT v24-sp2 (08/07/10) std as the newer version did not allow for proper SSH connections on my DIR-825 router, and I've installed the latest 1.6.3 version of bwmon and everything seems to be running as expected with the exception that the Live Bandwidth Stats HTML page shows no data other than a single row of 0s across.   Essentially no devices listed and none of the expected Bandwidth data regardless of normal or compact mode.

I've tried this in Firefox, Chrome and IE and I'm running Windows 10.

I am running the standard version, Lighttpd is unfortunately not an option, and both of the following files are accessible with the usage stats file seemingly being updated when I refresh every 10 seconds, just no corresponding info in the Live Bandwidth Stats page.

RouterIP/user/usage.js
RouterIP/user/usage_stats.js

Any help would be appreciated, thanks!
Hubert

**Comment by hcater** [comment]
Also, I see in the usage_stats.js page it lists the devices by their MAC addresses, will the Live Bandwidth Stats page also list them by MAC address, and if so is there a way to have them listed by their Host names?

**Comment by hcater** [comment]
I'm also having to use ext3 as ext4 was not an option on the older version install of DD-WRT.

If it helps, this is what I received when I stopped the script and then ran startup.sh as it looks like there are a few 'cannot remove' issues as in a few areas it looks to be looking at /tmp instead of /jffs when I installed.

BusyBox v1.13.4 (2010-08-07 04:38:31 CEST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

root@DD-WRT:~# /jffs/bwmon/stop.sh
killall: bwmon.sh: no process killed
backup completed
bandwidth monitor shutdown completed
root@DD-WRT:~# /jffs/bwmon/clean.sh
rm: cannot remove '/tmp/sorted_*.tmp': No such file or directory
root@DD-WRT:~# /jffs/bwmon/startup.sh
killall: bwmon-running.sh: no process killed
killall: bwmon-autobackup.sh: no process killed
killall: bwmon.sh: no process killed
killall: sleep: no process killed
cp: cannot stat '/tmp/www/usage.js': No such file or directory
backup completed
rm: cannot remove 'angular.min.js': No such file or directory
rm: cannot remove 'bootstrap.min.css': No such file or directory
rm: cannot remove 'bwmon.css': No such file or directory
rm: cannot remove 'bwmon.html': No such file or directory
rm: cannot remove 'bwmon.js': No such file or directory
rm: cannot remove 'bwreader.php': No such file or directory
rm: cannot remove 'mac-names.js': No such file or directory
rm: cannot remove 'ui-bootstrap-tpls.min.js': No such file or directory
bandwidth monitor shutdown completed
bandwidth monitor autobackup started use /jffs/bwmon/stop.sh to stop
bandwidth monitor started use /jffs/bwmon/bwmon-stop.sh to stop
root@DD-WRT:~# bandwidth monitor started with cycle time of 10 use /jffs/bwmon/stop.sh to stop

**Comment by vortex-5** [comment]
what does your /tmp/www directory look like?

**Comment by hcater** [comment]
root@DD-WRT:/www# ls
smb          splash.html  status.html  style        user

**Comment by vortex-5** [comment]
the folder in question is /tmp/www

**Comment by hcater** [comment]
Oops, here it is:

root@DD-WRT:/tmp/www# ls
angular.min.js            bwmon.js                  ui-bootstrap-tpls.min.js
bootstrap.min.css         bwreader.php              usage.js
bwmon.css                 font-awesome              usage_stats.js
bwmon.html                mac-names.js

**Comment by vortex-5** [comment]
that looks about right what do you get when you hit F12 when the browser is running anything on the error console?

**Comment by hcater** [comment]
Thanks for your help and this is what I could find from the 'console' tab once I hit F12, hopefully this is what you are looking for and it is helpful:

Error in parsing value for 'display'.  Declaration dropped. bwmon.css:15:10
Error in parsing value for 'display'.  Declaration dropped. bwmon.css:29:10
Unknown pseudo-class or pseudo-element '-webkit-inner-spin-button'.  Ruleset ignored due to bad selector. bootstrap.min.css:5:1544
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. bootstrap.min.css:5:1778
Unknown property 'orphans'.  Declaration dropped. bootstrap.min.css:5:2691
Unknown property 'widows'.  Declaration dropped. bootstrap.min.css:5:2700
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. bootstrap.min.css:5:3676
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. bootstrap.min.css:5:15705
Error in parsing value for 'margin-top'.  Declaration dropped. bootstrap.min.css:5:35736
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. bootstrap.min.css:5:35983
Unknown pseudo-class or pseudo-element '-ms-input-placeholder'.  Ruleset ignored due to bad selector. bootstrap.min.css:5:36914
Unknown pseudo-class or pseudo-element '-webkit-input-placeholder'.  Ruleset ignored due to bad selector. bootstrap.min.css:5:36962
Expected media feature name but found '-webkit-min-device-pixel-ratio'. bootstrap.min.css:5:37284
Error in parsing value for 'margin-top'.  Declaration dropped. bootstrap.min.css:5:38397
Unknown property 'touch-action'.  Declaration dropped. bootstrap.min.css:5:45338
Unknown property 'user-select'.  Declaration dropped. bootstrap.min.css:5:45446
Expected color but found 'auto'.  Expected color but found '-webkit-focus-ring-color'.  Expected end of value but found '-webkit-focus-ring-color'.  Error in parsing value for 'outline'.  Declaration dropped. bootstrap.min.css:5:45647
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:45993
Expected color but found 'solid\9 '.  Expected end of value but found 'solid\9 '.  Error in parsing value for 'border-top'.  Declaration dropped. bootstrap.min.css:5:56521
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:57888
Expected color but found 'solid\9 '.  Expected end of value but found 'solid\9 '.  Error in parsing value for 'border-bottom'.  Declaration dropped. bootstrap.min.css:5:58433
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:86486
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:86672
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:87391
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:87577
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:88017
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:88203
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:88649
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:88835
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:89279
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:89465
Unknown property 'zoom'.  Declaration dropped. bootstrap.min.css:5:89901
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:107144
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:107253
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:108462
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:108515
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:109684
Unknown property 'line-break'.  Declaration dropped. bootstrap.min.css:5:109721
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:109746
Unknown property 'line-break'.  Declaration dropped. bootstrap.min.css:5:111728
Expected media feature name but found 'transform-3d'. bootstrap.min.css:5:113566
Expected media feature name but found '-webkit-transform-3d'. bootstrap.min.css:5:113581
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:114872
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:114941
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:115028
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:115110
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:115287
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:115484
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:115571
Error in parsing value for 'background-image'.  Declaration dropped. bootstrap.min.css:5:115653
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:115830
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. bootstrap.min.css:5:116055
Expected color but found '#\30 00\9 '.  Error in parsing value for 'background-color'.  Declaration dropped. bootstrap.min.css:5:117004
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. font-awesome.min.css:4:660
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.min.css:4:1899
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.min.css:4:2062
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.min.css:4:2228
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.min.css:4:2399
Expected 'none', URL, or filter function but found 'progid'.  Error in parsing value for 'filter'.  Declaration dropped. font-awesome.min.css:4:2572
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1): status=2152398868 source: http://192.168.1.1/user/font-awesome/fonts/fontawesome-webfont.woff2?v=4.5.0 font-awesome.min.css:4:14
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2): status=2152398868 source: http://192.168.1.1/user/font-awesome/fonts/fontawesome-webfont.woff?v=4.5.0 font-awesome.min.css:4:14
downloadable font: download failed (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:3): status=2152398868 source: http://192.168.1.1/user/font-awesome/fonts/fontawesome-webfont.ttf?v=4.5.0 font-awesome.min.css:4:14
downloadable font: no supported format found (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:5) source: (end of source list) font-awesome.min.css:4:14
NetworkError: A network error occurred. <unknown>

**Comment by vortex-5** [comment]
Nothing particularly looks like a cause except for the very last line however there isn't enough additional information just "Network Error"

Sadly it does appear that the error log reveals that people not using lighttpd have issues retrieving the font-awsome libraries so they will get corrupted images so I'm going to create an issue and ticket for that.

**Comment by hcater** [comment]
Thanks for taking a look
