### ISSUE TITLE
 Future traffic quota may add this feature

### ISSUE THREAD

**Issue by houzi-** [vortex-5/ddwrt-bwmon#30]
Such as the title , this feature should be able to achieve it through iptables ?

**Comment by vortex-5** [comment]
I don't think this is achievable when you add a traffic quota I expect you want to be able to cut off machines that hit the quota. That's not a feature that can be added easily and most likely it'll cut off other machines when a new iptables rule is inserted.

Also this seems to be beyond the scope of this project.

**Comment by vortex-5** [comment]
Closing for now there isn't really a way to do this just through ip tables potentially another fork can look at the data aquired in usage_stats.js and use that to somehow lock the iptables but I'm not clever enough to figure that out yet.
