### ISSUE TITLE
No data displayed in bwmon.html

### ISSUE THREAD

**Issue by smirciat** [vortex-5/ddwrt-bwmon#34]
I have set this up for release 1.8.0 per the instructions on a Buffalo WZR-HP-G300NH running DD-WRT, with an ext3 formatted usb drive mounted to /jffs and no  lighttpd support.  The scripts seem to run fine, and there is data in /tmp/data/usage.js.  When loading http://routerip/user/bwmon.html, the template loads fine, but there is no data in the table.  Build is 14998, could that be too old for this? It seems like I missed something simple in the setup, but what could it be?

**Comment by sparkym3** [comment]
I have this same router and same setup, but NTFS, and the table is blank when I get my password prompt but as soon as I cancel the password prompt all works fine. Do you have a password setup on the router?

**Comment by smirciat** [comment]
I did get the password prompt, and I entered the root login info, which is the only user I have setup on the router.  Still no data though

**Comment by smirciat** [comment]
OK I read what you wrote, hit cancel, and all is well!  Thanks!
