### ISSUE TITLE
Will it work even if I set the DDWRT page with port?

### ISSUE THREAD

**Issue by target123** [vortex-5/ddwrt-bwmon#36]
Will the bandwidth monitor still work even if the main config page is on a port other than 80?

**Comment by vortex-5** [comment]
I have not tested that mode of operation in theory yes.

**Comment by target123** [comment]
what port would i access the page then?

**Comment by vortex-5** [comment]
the same port you use to access your router's config page. I.E. if your outer can be reached by 192.168.0.1:8080 then you would access the page at 192.168.0.1:8080/user/bwmon.html

if you are using the php version then you can access it via whatever the PHP page is in your router setup (only routers with 32MB of flash or more have this option)

**Comment by target123** [comment]
What do you mean with the PHP option, would you mind elaborating the advantages or differences of having a PHP in ddwrt?

Thanks

**Comment by vortex-5** [comment]
When using the webserver the script can access a php service which is allowed to execute commands on the router. 

without the webserver the script is read only.

The main advantage you will observe is the php server version will have less overhead as it only checks for usage every 60 seconds vs 10 seconds. In addition when the web page is visited you will auto refresh the data every 1 second vs 10 seconds so the best of both worlds more responsive when you have the traffic page open and less resource usage when you are not looking at the live traffic page.
