### ISSUE TITLE
Can't use wget for downloading

### ISSUE THREAD

**Issue by target123** [vortex-5/ddwrt-bwmon#37]
![screen shot 2016-09-07 at 12 55 23 am](https://cloud.githubusercontent.com/assets/20024570/18282959/d7a5bf58-7495-11e6-88df-ba2bd4aed47d.png)

Nothing is happening, is there anything I should do to download?

**Comment by vortex-5** [comment]
wget https://github.com/vortex-5/ddwrt-bwmon/releases/download/1.8.0/bwmon.tar.gz should be the correct url.
