### ISSUE TITLE
Script timing question

### ISSUE THREAD

**Issue by creited** [vortex-5/ddwrt-bwmon#38]
How is this measured under 10 seconds? Is it a mean which is displayed?

How would you suggest to change this timing cycle? What should be changed on the script files?

Thank you!

**Comment by vortex-5** [comment]
10 cycles is when every sample is taken it's hard coded and part of bwmonitor-running.sh

bwmon.js also contains a bunch of SCRIPT_INTERVAL = 10 fields.

if you are running lighttpd this is bypassed the script makes a query and can sample how ever often it likes.
