### ISSUE TITLE
getName/macIpDns broken with upper case MAC change

### ISSUE THREAD

**Issue by esassaman** [vortex-5/ddwrt-bwmon#41]
Version 1.8.0 freshly installed

I'm not getting names in the device column, nor IP addresses. As a test I changed the macIpDns() call in bwmon.html on line 74 to macIpDns[device.mac.toLowerCase() and getNames() call to getName(device.mac.toLowerCase()) forcing lower case in each instance and that fixed the problem. Somehow upper case MAC IDs are being passed into both functions but all the MAC IDs in $scope.macNames are lower case, no match and only mac addresses were returned from each function as a fallback.

**Comment by vortex-5** [comment]
I just got back from vacation Ill investigate this tomorrow.

**Comment by vortex-5** [comment]
Thanks for your bugfix I have updated the current release to account for your router variant. Not all routers are consistent with the dns mac entries going forward I'll probably have to ensure all references to the internal mac tables are corrected to be lowercase.

Please check out release 1.8.1 for your fix: https://github.com/vortex-5/ddwrt-bwmon/releases/tag/1.8.1

**Comment by vortex-5** [comment]
Commits relevant for your fix can be found here: https://github.com/vortex-5/ddwrt-bwmon/commit/741c590990af711517e1d67a40b269eb38dc5c2b

**Comment by esassaman** [comment]
The fix works great! Thank you. BTW I have a Asus RT-N16 router running DD-WRT v24-sp2 (08/12/10) mega, sorry for not making a note of that earlier!
