### ISSUE TITLE
Fix some minor layout issues introduced with the new dark theme

### ISSUE THREAD

**Issue by vortex-5** [vortex-5/ddwrt-bwmon#48]
Another user contributed a dark theme. 

The only minor problem is on mobile (responsive design) the buttons don't look quite right.

We need to add some wrapping to the layout so the buttons look right.

**Comment by J3n50m4t** [comment]
I've looked into this "bug" and realised, it's no bug.

Bootstrap just doesn't support fully responsive btn-groups . [Bootstrap Issue #7252](https://github.com/twbs/bootstrap/issues/7252)

We could manipulate the bootstrap or use some extra class as I did in #49.

Also, we could use vertical groups, but it would duplicate allot of content.
Little example for the first buttongroup
```
<div class="btn-group hidden-xs">
	<label class="btn btn-default" ng-model="displayDensity" btn-radio="'Normal'">Normal</label>
	<label class="btn btn-default" ng-model="displayDensity" btn-radio="'Compact'">Compact</label>
</div>
<div class="btn-group-vertical visible-xs">
	<label class="btn btn-default" ng-model="displayDensity" btn-radio="'Normal'">Normal</label>
	<label class="btn btn-default" ng-model="displayDensity" btn-radio="'Compact'">Compact</label>
</div>
```
![vertical](https://cloud.githubusercontent.com/assets/13681191/24251882/ed761684-0fdb-11e7-952f-7c6db794cf85.gif)
_made a copy&paste mistake in the gif - sorry_

**Comment by vortex-5** [comment]
I was just going to change the row to not use bootstrap alignment

I.E. I was going to change the row to 

```
<div style="display: flex; flex-wrap: wrap">
  <item>...
  <item>...
</div>
```

then fiddle around with it. I wouldn't have to use @media queries.

I use flex at work a lot to compensate when stability is more important vs aesthetics.

**Comment by vortex-5** [comment]
Added some wrapping the whole thing is pretty slick now new version will be drafted.
