### ISSUE TITLE
Can't get html to load

### ISSUE THREAD

**Issue by deadman36g** [vortex-5/ddwrt-bwmon#5]
Having trouble getting this going.

I followed the intructions from github and everything seemed to be working but the user/bwmin.html page will not load for me.

I have it installed to /opt/ 

[code]
root@DD-WRT:/opt# wget https://github.com/vortex-5/ddwrt-bwmon/releases/download/1.2/bwmon.tar.gz
Connecting to github.com (192.30.252.131:443)
Connecting to s3.amazonaws.com (54.231.14.96:443)
bwmon.tar.gz         100% |*********************************************************************************************************************************************************| 85261   0:00:00 ETA
root@DD-WRT:/opt# tar -xzvf bwmon.tar.gz
bwmon/
bwmon/backup.sh
bwmon/bwmon-autobackup.sh
bwmon/bwmon-dnsmasq.sh
bwmon/bwmon-running.sh
bwmon/bwmon.sh
bwmon/clean.sh
bwmon/install.sh
bwmon/start.sh
bwmon/startup.sh
bwmon/stop.sh
bwmon/www/
bwmon/www/angular.min.js
bwmon/www/bootstrap.min.css
bwmon/www/bwmon.css
bwmon/www/bwmon.html
bwmon/www/bwmon.js
bwmon/www/mac-names.js
bwmon/www/ui-bootstrap-tpls-0.12.1.min.js
root@DD-WRT:/opt# cd /opt/bwmon/ && sh install.sh
Installation completed.
Type /opt/bwmon/startup.sh to start the script
You can visit the stats page by navigating to http://routerip/user/bwmon.html
[/code]

as you can see my terminal looks good.

for router startup command I have, 

/opt/bwmon/startup.sh

so I am not sure my problem.

I should note the following
I have a r7000 router (arm)
Firmware: DD-WRT v3.0-r27365M (06/18/15) kongac
Also, my flash drive is formatted to ext2

**Comment by vortex-5** [comment]
the page you're looking for is user/bwmon.html

**Comment by deadman36g** [comment]
That was the page I was loading, but alas, it is there now perhaps I was not being patient enough? Anyways, vortex-5 thanks for this awesome script :)

**Comment by vortex-5** [comment]
By default the script is designed to start 1min after router first boots.

This is so the script does not compete with CPU resources as the router is getting started and things are getting setup.

you can adjust this in the startup script if you want a faster response. Just keep min mind this was done on purpose to make sure the router is in a "good state" before starting the bandwidth monitoring services. Dropping the startup wait too low may cause issues but seeing how you have a fast router you can drop it down to maybe 10 seconds if you're impatient.

**Comment by deadman36g** [comment]
lol, I am indeed impatient at times. But that certainly makes sense my previous router took a good 2-3 minutes to fully boot. I have a quick off-topic question if you don’t mind. Under the device column I am only getting MAC ID's, I would prefer Hostname (or is there an option for both?). Is this me being impatient again and not allowing the script time to fetch this information?

**Comment by vortex-5** [comment]
There are 2 ways of decoding host names. If you don't want to manually assign ip's you can add the hostnames to mac-names.js.

However if you want a more "on the router" manageable way you need to assign static DHCP leases on the router under services once you're devices have DHCP entries in there they will automatically show up named on the page.

At present there is no way to assign names directly from the web page since it would only be able to store that on the browser. The DDWRT micro web server does not allow script execution that writes to the router via http request.

**Comment by deadman36g** [comment]
Awesome, while I do have a few static leases, I had been planning to set more up, so I guess I will do that now. Thanks for your quick responses vortex-5
