### ISSUE TITLE
Making Dark Theme Default

### ISSUE THREAD

**Issue by target123** [vortex-5/ddwrt-bwmon#50]
Hi,

Would it be possible to make Dark Theme the default one without having to manually pressing the dark theme button every time we access the page?

Thanks in advance,

**Comment by vortex-5** [comment]
If you enable cookies it remembers you want dark theme.

**Comment by target123** [comment]
Would it not be possible to be set as default system wide?

**Comment by vortex-5** [comment]
For security reasons the web page cannot write anything to the router by design. If you want this you can modify the J's file to default to the dark theme.

**Comment by target123** [comment]
Would you mind showing how?

Thanks! 

Btw! it would be nice to provide an option during installation to ask whether dark or light theme should be the default one! :)

**Comment by vortex-5** [comment]
I didn't write the dark theme feature this would be better directed at the original author. 

I'm out of the country and do not have access to a computer in the mean time.

**Comment by J3n50m4t** [comment]
In my fork i created an branch dark_default

**Comment by J3n50m4t** [comment]
I will look into this later today.

**Comment by vortex-5** [comment]
You know I like the dark theme more too recently I think I may take your commit up on that and make the dark theme default.

(And wait for any complaints lol)

expect an updated version soon.

**Comment by vortex-5** [comment]
After a long wait the dark theme is now default and the front page has been updated with a new screenshot to reflect his.
