### ISSUE TITLE
Not working with 33492

### ISSUE THREAD

**Issue by danmed** [vortex-5/ddwrt-bwmon#54]
I'm not getting refreshing of speeds / data on 33492...

Router ModelTPLINK WR1043ND V2
Firmware Version DD-WRT v3.0-r33492 std (10/10/17)

2 different browsers (on different systems) report different stats and once they've refreshed once, they never refresh again..

**Comment by vortex-5** [comment]
Hmm.. Is this the lighttpd version running or the non lighttpd version.

I'm currently running this on the lighttpd version and I do see speed updates I haven't checked if anything broke in the non webserver version.

**Comment by danmed** [comment]
I don't have light as an option.. I've tried on 31221 and it seems ok.. the
problem is I'd like the latest version to be safe with the latest dnsmasq
patches

**Comment by vortex-5** [comment]
I'll have to see what changed with the recent version with the DNS masq changes this weekend.

**Comment by danmed** [comment]
Thank you :)

**Comment by vortex-5** [comment]
Hi I was able to draft up a fix tonight if you have time please give this a test and if it addresses your issue I'll move this from pre-release status to release.

The main change it appears now the DDWRT web server says that there are no changes to the files in the /user/ directory so the browser continues to use the cached version even if newer data is available.

This patch hopefully addresses that issue.

https://github.com/vortex-5/ddwrt-bwmon/releases/tag/1.9.1

**Comment by danmed** [comment]
That looks to be working.. thank you :)

**Comment by vortex-5** [comment]
Ok cool I'll change the status of the release from pre-release to release then.
