### ISSUE TITLE
Data usage is not being updated

### ISSUE THREAD

**Issue by hawxxx** [vortex-5/ddwrt-bwmon#64]
All of the devices on my network have the same data usage from weeks ago but this is not being updated. Last seen is the only field that is being updated.

**Comment by hawxxx** [comment]
Update: It seems to be working now that I have disabled Shortcut Forwarding Engine (SFE)

**Comment by vortex-5** [comment]
I think this was mentioned in the past it tends to be hardware specific it seems that SFE sometimes bypasses the routing hardware and as a result nothing can get counted through the firewall for usage stats.
