### ISSUE TITLE
Does this still work? 

### ISSUE THREAD

**Issue by deltabravozulu** [vortex-5/ddwrt-bwmon#75]
I have this installed on a router running DD-WRT v3.0-r47510 std (10/04/21). I swapped out /jffs for /opt after having no luck getting any data to populate to 192.168.1.1/user/bwmon.html or 192.168.1.1:8000/bwmon.html (with lighttpd running). 

This still ended up not working--it seems to be due to bwreader.cgi not being loaded (the router spits out a 404 error page where bwreader.cgi should be, and it is definitely in the bwmon/www directory and the /tmp/www directory.

**Comment by vortex-5** [comment]
I have it working on the latest version. In the most recent versions lighttpd is no longer required to get it to work although you can use it optionally.

After running install.sh you should be able to run start.sh it will schedule a cron job to populate all the correct folders in 120 sec.

The user/bwmon.html folder reads from /tmp/www

**Comment by vortex-5** [comment]
It appears DDWRT has decided on certain models to replace the 404 errors with a 404 "friendly html page" 

Unfortunately this breaks detection as it gives a status 200 successful

I have patched the code to now read the web page served and look for any indications for 404 hopefully they don't change how this works too much.
